version: '3'

services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: kotlin-jpa-db
    ports:
      - 23302:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
